export const SEARCH_ERROR = 'SEARCH_ERROR';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const INVALID_DATA = 'INVALID_DATA';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
